#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os

BOM = b'\xef\xbb\xbf'
toggle_bom = None


def _remove_bom(content, abs_file_path):
    if content.startswith(BOM):
        with open(abs_file_path, mode='wb') as out:
            out.write(content[3:])
        print("Remove %s's bom" % abs_file_path)


def _add_bom(content, abs_file_path):
    if not content.startswith(BOM):
        content = BOM + content
        with open(abs_file_path, mode='wb') as out:
            out.write(content)
        print("add BOM to %s" % abs_file_path)


def _convert(dir):
    for root, _, files in os.walk(dir):
        for file in files:
            *_, ext = file.split(".")
            if ext not in ("cpp", "h", "hpp", "cc", "c"):
                continue

            abs_file_path = os.path.abspath(os.path.join(root, file))

            with open(abs_file_path, mode='rb') as input:
                content = input.read()

            global toggle_bom
            if toggle_bom is None:
                if content.startswith(BOM):
                    toggle_bom = _remove_bom
                else:
                    toggle_bom = _add_bom

            toggle_bom(content, abs_file_path)


def main():
    global toggle_bom
    if len(sys.argv) == 2:
        if sys.argv[-1] == "true":
            toggle_bom = _add_bom
        elif sys.argv[-1] == "false":
            toggle_bom = _remove_bom

    _convert('.')


if __name__ == "__main__":
    main()
